### PR TITLE
Fix erroneous conversion of object to string

### LINKED ISSUE #1290: TypeError: r is null on statistics pages
This one is intermittent and happens on stage and prod so it's not related to the recent jquery-migrate changes. This is also why I'm logging this now too to keep it separate.

Using unminified srcs via a proxy it points to this line https://github.com/mozilla/olympia/blob/d8aef0b88a5fd20d4413a37807e9ae79c7602fa8/static/js/impala/stats/dateutils.js#L43

It's this line: `by = +match[1];`

```js
backward : function(by, unit) {
  if (typeof by == 'string') {
    var match = intervalRegex.exec(by);
    by = +match[1];
    unit = match[2];
  }
  return this.forward(-by, unit);
},
```

The real error is `TypeError: match is null`

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #1290

To test look at a stats page and change the dates in the datepicker. When you refresh the dates should be restored from session storage and as the error is gone - the data is displayed as expected.

### CODE REVIEW

File: static/js/impala/stats/stats.js [hunk 1]
```diff
@@ -41,7 +41,21 @@
...
             var ssView = JSON.parse(sessionStorage.getItem('stats_view'));
-            initView.range = _.escape(ssView.range || initView.range);
+
+            // The stored range is either a string or an object.
+            if (ssView.range && typeof ssView.range === 'object') {
+                var objRange = ssView.range;
+                Object.keys(objRange).forEach(function(key) {
+                    var val = objRange[key];
+                    if (typeof val === 'string') {
+                      objRange[key] = _.escape(val);
```
Comment (magopian) [inline static/js/impala/stats/stats.js]: :+1:

**Comment by magopian** [comment]
very good!

r+
